# general settings
name: SMID
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 666

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_SMIDImage
    # interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_gt: /media/lht/disk/dataset/SMID/SMID_Long_np
    dataroot_lq: /media/lht/disk/dataset/SMID/SMID_LQ_np
    train_size: [960, 512]
    cache_keys: ~
    cache_data: true
    padding: new_info
    # testing_dir: pair11,pair21,pair1,pair19,pair4,pair9

    filename_tmpl: '{}'
    io_backend:
      type: disk

    N_frames: 5     # how many frames as a input.
    # data argument
    use_flip: true
    use_rot: true
    color: RGB
    
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4

    ### -------------Progressive training--------------------------
    # mini_batch_sizes: [8,5,4,2,1,1]             # Batch size per gpu   
    # iters: [92000,64000,48000,36000,36000,24000]
    # gt_size: 384   # Max patch size for progressive training
    # gt_sizes: [128,160,192,256,320,384]  # Patch sizes for progressive training.
    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 256x256---------
    mini_batch_sizes: [4]   
    iters: [300000]
    gt_size: 256
    gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_SMIDImage
    dataroot_gt: /media/lht/disk/dataset/SMID/SMID_Long_np
    dataroot_lq: /media/lht/disk/dataset/SMID/SMID_LQ_np
    cache_data: true
    N_frames: 5
    padding: new_info
    train_size: [960, 512]

    io_backend:
      type: disk

# network structures
network_g:
  type: DRSformer
  inp_channels: 3
  out_channels: 3
  # middle_channels: 16 #the middle channels of illumination estimator
  dim: 16
  num_blocks: [2,4,4,8]
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 300000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [100000, 200000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 1e4
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      # better: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
      # better: higher

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
